skip_local_validator = true

[toolchain]

[features]
resolution = true
skip-lint = false

[programs.devnet]
phpa_solana = "8PsEGMMHa76MzM2fXGFSt1x8fic5RcAza5cjLV6NCDd4"

[provider]
cluster = "devnet"
wallet = "/Users/yujiwakabayashi/solana/phpa-deploy-keypair.json"

[scripts]
test = "cargo test"

[hooks]
